name: Build and push Docker images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: api
            dockerfile: Dockerfile.api
          - name: worker
            dockerfile: Dockerfile.worker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_SECERT }}

    - name: Build and push ${{ matrix.name }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: hydro2070/complier-${{ matrix.name }}:latest
